vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: /Image/Event
            upload_destination: '%kernel.project_dir%/public/Image/Event'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
