vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: '%app.path.event_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.event_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: false

        goodies:
            uri_prefix: '%app.path.goodies_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.goodies_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        photo_event:
            uri_prefix: '%app.path.photo_event_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.photo_event_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
